### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId

### ISSUE THREAD

**Issue by mukeshdiscovery** [blueshift-labs/Blueshift-Android-SDK#333]
Here is the app config :

'compileSdk': 33,
'minSdk'    : 21,
'minSdkTv'  : 21,
'targetSdk' : 31,
'buildTools': '30.0.2'

Blueshift Lib 
'blueshiftSDK' : "com.blueshift:android-sdk:3.3.0"

Firebase Libs
'analytics'    : "com.google.firebase:firebase-analytics:20.1.2",
'**messages'     : "com.google.firebase:firebase-messaging:20.2.4",**
'crashlytics'  : "com.google.firebase:firebase-crashlytics:18.2.5",
'perf'         : "com.google.firebase:firebase-perf:20.0.4",
'core'       : "com.google.firebase:firebase-core:18.0.1",
'database'     : "com.google.firebase:firebase-database-ktx:19.3.0",
'remoteConfig' : "com.google.firebase:firebase-config:21.0.1"

With this config, blueshift notification work fine. 

Recently when we tested on android 13 device and we have got this crash in Crashlytics.Here is the crash info -

Fatal Exception: java.lang.IllegalArgumentException: com.scripps.android.foodnetwork: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
       at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
       at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:491)
       at android.app.PendingIntent.getActivity(PendingIntent.java:477)
       at android.app.PendingIntent.getActivity(PendingIntent.java:441)
       at com.google.firebase.messaging.CommonNotificationBuilder.createContentIntent(CommonNotificationBuilder.java:125)
       at com.google.firebase.messaging.CommonNotificationBuilder.createNotificationInfo(CommonNotificationBuilder.java:27)
       at com.google.firebase.messaging.CommonNotificationBuilder.createNotificationInfo(CommonNotificationBuilder.java:9)
       at com.google.firebase.messaging.DisplayNotification.handleNotification(DisplayNotification.java:27)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:76)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:55)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:34)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:23)  

I dont know the root cause of this whether Is it caused by blueshift sdk or firebase messaging libs. Since we are using latest blueshift SDK, I thought of updating the  firebase messaging lib.

When I try to update firebase-messaging lib to **firebase-messaging:23.1.2** and try to do blueShift.initialize(this), We get this exception:

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
        at com.blueshift.util.DeviceUtils.iidPkgNameCombo(DeviceUtils.java:96)
        at com.blueshift.util.DeviceUtils.getDeviceId(DeviceUtils.java:83)
        at com.blueshift.BlueshiftAttributesApp.sync(BlueshiftAttributesApp.java:397)
        at com.blueshift.Blueshift.sendEvent(Blueshift.java:689)
        at com.blueshift.Blueshift.access$200(Blueshift.java:62)
        at com.blueshift.Blueshift$5.run(Blueshift.java:758)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/~~zmqCzndJPd8r621RLR-Azw==/com.scripps.android.foodnetwork-6aD2XdwPhfFzQwcM15Sm6g==/base.apk"],nativeLibraryDirectories=[/data/app/~~zmqCzndJPd8r621RLR-Azw==/com.scripps.android.foodnetwork-6aD2XdwPhfFzQwcM15Sm6g==/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)

Pls help

Thanks

**Comment by rahulrvp** [comment]
Hi @mukeshdiscovery, thanks for reaching out to us.

`com.blueshift:android-sdk` is the Support Library compatible version of our SDK which will soon be marked as deprecated. This one can not be used alongside latest firebase library versions as those firebase libraries depend on AndroidX dependencies.

We have an AndroidX compatible version of our SDK which is named `com.blueshift:android-sdk-x`. Please use this library in your project and the issue should get resolved.

I am closing this issue now. Feel free to send an email to support@bueshift.com if you have any further questions or if the issue persists.
