### ISSUE TITLE
Crash in Blueshift.getDeviceParams()

### ISSUE THREAD

**Issue by justincpollard** [blueshift-labs/Blueshift-Android-SDK#53]
I just released my app into production with the Blueshift SDK installed and I'm seeing some crashes. Here's the stacktrace:

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
Caused by java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:792)
       at java.util.HashMap$EntryIterator.next(HashMap.java:829)
       at java.util.HashMap$EntryIterator.next(HashMap.java:827)
       at java.util.AbstractMap.putAll(AbstractMap.java:380)
       at java.util.HashMap.putAll(HashMap.java:508)
       at com.blueshift.Blueshift.getDeviceParams(Blueshift.java:106)
       at com.blueshift.Blueshift.sendEvent(Blueshift.java:235)
       at com.blueshift.Blueshift.access$200(Blueshift.java:45)
       at com.blueshift.Blueshift$2.doInBackground(Blueshift.java:342)
       at com.blueshift.Blueshift$2.doInBackground(Blueshift.java:338)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by aswani521** [comment]
Hey Justin we are looking into this issue, will get back to you asap

**Comment by justincpollard** [comment]
A little more info on our use of the SDK:

I'm initializing the SDK in an `@Provides` annotated method called by our dependency injection framework:

```
  @Provides
  @Singleton
  public Blueshift provideBlueshift(Application application) {
    Configuration config = new Configuration();
    config.setAppIcon(R.drawable.ic_launcher);
    config.setApiKey("blueshift_key_here");
    Blueshift blueshift = Blueshift.getInstance(application);
    blueshift.initialize(config);
    return blueshift;
  }
```

Through our dependency graph, this method is invoked during `Application.onCreate()`.

After initialization, the first method I end up calling is `Blueshift.identifyUserByDeviceId()`. I kick off a new thread in my main activity that calls Android's `AdvertisingIdClient.getAdvertisingIdInfo()` method, the id of which I pass to `Blueshift.identifyUserByDeviceId()` without any extra `details`.

Other events might be called at any point during runtime. There's no guarantee on which thread those methods are called. Many of them are called on the main thread while others are called on background threads; it depends on what actually triggers the event.

Here are the methods that call Blueshift:

```
  /**
   * Processes the "Screen" events.
   */
  private void screen(String screenName) {
    blueshift.trackScreenView(screenName, shouldBatchEvents);
  }

  /**
   * Process the "Message Sent" event.
   */
  private void lead(AnalyticsEvent event) {
    String id = getStringId(event.getAllEventProps());
    if (id != null) {
      HashMap<String, Object> sku = new HashMap<>();
      sku.put("sku", id);
      blueshift.trackEvent("lead", sku, shouldBatchEvents);
    }
  }

  /**
   * Process the "Multimessage Sent" event.
   */
  @SuppressWarnings("unchecked")
  private void leads(AnalyticsEvent event) {
    Map<String, Object> props = event.getAllEventProps();
    if (props != null) {
      long[] listingIds = (long[]) props.get("listing_ids");
      long[] buildingIds = (long[]) props.get("building_ids");
      HashMap<String, Object> sku = new HashMap<>();
      sku.put("sku", combineListingAndBuildingIds(listingIds, buildingIds));
      blueshift.trackEvent("lead", sku, shouldBatchEvents);
    }
  }

  /**
   * Process the "Alert Created" event.
   */
  private void alert(AnalyticsEvent event) {
    blueshift.trackEvent("alert",
            putParamsIntoEventMetadata(mapEventPropsToFilterProps(event.getAllEventProps())),
            shouldBatchEvents);
  }

  /**
   * Process the "Click Fav" event.
   */
  private void favorite(AnalyticsEvent event) {
    String id = getStringId(event.getAllEventProps());
    if (id != null) {
      HashMap<String, Object> sku = new HashMap<>();
      sku.put("sku", id);
      blueshift.trackEvent("favorite", sku, shouldBatchEvents);
    }
  }

  /**
   * Process the "Screen: Listing Detail" event.
   */
  private void productView(AnalyticsEvent event) {
    Map<String, Object> props = event.getAllEventProps();
    String id = getStringId(props);
    if (id != null) blueshift.trackProductView(id, 0, shouldBatchEvents);
  }

  @SuppressWarnings("unchecked")
  private void search(AnalyticsEvent event) {
    Map<String, Object> eventProps = event.getAllEventProps();
    if (eventProps != null) {
      long[] listingIds = (long[]) eventProps.get("listing_ids");
      long[] buildingIds = (long[]) eventProps.get("building_ids");

      Object numResults = eventProps.get("num_results");
      Object page = eventProps.get("page");

      HashMap<String, Object> props = mapEventPropsToFilterProps(eventProps);
      props.putAll(getEventLocationInfo(eventProps));

      // Wrap our filter props in "event_metadata"
      props = putParamsIntoEventMetadata(props);

      // Add the following as top-level props
      props.put("skus", combineListingAndBuildingIds(listingIds, buildingIds));
      props.put("number_of_results", numResults != null ? (int) numResults : -1);
      props.put("page_number", page != null ? (int) page : -1);

      blueshift.trackEvent("list_search", props, shouldBatchEvents);
    }
  }
```

**Comment by nipunbhatia** [comment]
Hey Justin,

Can you please confirm which version of the SDK are you using. We recommend you use v 1.0.4 for Android.

**Comment by justincpollard** [comment]
Aw, I now realize I'm way behind ... was using v0.7.0 because that's what was shown in the documentation examples. I'll change to the latest version and release that. Thanks!
