### ISSUE TITLE
Crash bug in Blueshift: BroadcastReceiver components are not allowed to register to receive intents

### ISSUE THREAD

**Issue by justincpollard** [blueshift-labs/Blueshift-Android-SDK#54]
Hi all,

After realizing that my prior bug (https://github.com/blueshift-labs/Blueshift-Android-SDK/issues/53) was probably related to using an old SDK, I released another version into production this morning that uses version 1.0.4. Since then, Crashlytics is telling me there have been 48 crashes from 41 users on the following type:

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:318)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
Caused by android.content.ReceiverCallNotAllowedException: BroadcastReceiver components are not allowed to register to receive intents
       at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:105)
       at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:94)
       at com.blueshift.Blueshift.<init>(Blueshift.java:93)
       at com.blueshift.Blueshift.getInstance(Blueshift.java:106)
       at com.blueshift.httpmanager.request_queue.RequestQueue$sendRequestTask.doInBackground(RequestQueue.java:146)
       at com.blueshift.httpmanager.request_queue.RequestQueue$sendRequestTask.doInBackground(RequestQueue.java:127)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

You can see the details of my implementation in the ticket referenced above (https://github.com/blueshift-labs/Blueshift-Android-SDK/issues/53)

**Comment by rahulrvp** [comment]
hey @justincpollard 

We'd like to know if the `getInstance()` method of the `Blueshift` class is being called anywhere from your app using a BroadcastReceiver's `context`.

**Comment by justincpollard** [comment]
Hi @rahulrvp,

I don't believe so. The only call to `Blueshift.getInstance()` uses our `Application` context.

**Comment by rahulrvp** [comment]
This issue is fixed. Please use the latest version v1.0.5 from now on.

**Comment by justincpollard** [comment]
I'll integrate it and let you know if I encounter anymore problems! Thanks :-)

**Comment by justincpollard** [comment]
By the way, haven't encountered this issue in my latest production builds.
