### ISSUE TITLE
Crash bug in GCMBaseIntentService

### ISSUE THREAD

**Issue by justincpollard** [blueshift-labs/Blueshift-Android-SDK#62]
v1.0.8 of the SDK

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
       at com.blueshift.gcm.GCMBaseIntentService.onHandleIntent(GCMBaseIntentService.java:232)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by aswani521** [comment]
this got fixed in v1.0.9, closing out
